spring:
  mvc.view:
    prefix: /WEB-INF/
    suffix: .jsp

logging.level:
  root: WARN
  org.superbiz.moviefun: DEBUG

s3:
  accessKey: AKIAVT7FZ27LQ4QPFP56
  secretKey: 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
  bucketName: sjlee5.lsis.com

albums:
  url: http://localhost:8081/albums
movies:
  url: http://localhost:8082/movies